version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/php:7.4-node
    steps:
      - checkout
      - run:
          name: Install Terminus
          command: |
            curl -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar
            php installer.phar install
            echo 'export PATH="$HOME/.composer/vendor/bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Authenticate with Pantheon
          command: |
            terminus auth:login --machine-token=$PANTHEON_MACHINE_TOKEN
      - run:
          name: Push Code to Pantheon
          command: |
            terminus connection:set $PANTHEON_SITE_NAME.$PANTHEON_ENV git
            git remote add pantheon ssh://codeserver.dev.$PANTHEON_SITE_NAME@code.getpantheon.com:2222/~/repository.git || true
            git push pantheon main --force

workflows:
  version: 2
  deploy_to_pantheon:
    jobs:
      - deploy
